// Test-only stub for convex/_generated/api (real file is auto-generated by `npx convex dev`)
export const api = {
  subscriptions: {
    getSubscription: "subscriptions:getSubscription" as any,
  },
} as any;
