// Test-only stub for convex/_generated/api (real file is auto-generated by `npx convex dev`)
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const api: any = {
  subscriptions: {
    getSubscription: "subscriptions:getSubscription",
  },
};
